[build-system]
requires = ["setuptools<65",
            "wheel", 
            "numpy==2.0.0; python_version > '3.8'",
            "oldest-supported-numpy; python_version <= '3.8'"]
build-backend = "setuptools.build_meta"


