var searchData=
[
  ['pb_0',['pb',['../classpyoculus_1_1problems_1_1qfm__bfield_1_1_q_f_m_bfield.html#acba07517c3111b1312c2bbdea5008bde',1,'pyoculus::problems::qfm_bfield::QFMBfield']]],
  ['pi_1',['pi',['../namespacespecconstants.html#afb7f945629e23fb17338af7caaf8dbe4',1,'specconstants']]],
  ['pi2_2',['pi2',['../namespacespecconstants.html#aead637195238fbd0aa489c4a29189125',1,'specconstants']]],
  ['plusminus_3',['plusminus',['../classpyoculus_1_1problems_1_1spec__pjh_1_1_s_p_e_c_p_j_h.html#a078c388ee64e03462117c74f8da15825',1,'pyoculus::problems::spec_pjh::SPECPJH']]],
  ['poincare_5fplot_5ftype_4',['poincare_plot_type',['../classpyoculus_1_1problems_1_1base__problem_1_1_base_problem.html#aa93c0d34f5d13b28e1b6ed8761b96b87',1,'pyoculus.problems.base_problem.BaseProblem.poincare_plot_type'],['../classpyoculus_1_1problems_1_1cylindrical__problem_1_1_cylindrical_problem.html',1,'pyoculus.problems.cylindrical_problem.CylindricalProblem.poincare_plot_type'],['../classpyoculus_1_1problems_1_1qfm__bfield_1_1_q_f_m_bfield.html',1,'pyoculus.problems.qfm_bfield.QFMBfield.poincare_plot_type'],['../classpyoculus_1_1problems_1_1spec__bfield_1_1_s_p_e_c_bfield.html',1,'pyoculus.problems.spec_bfield.SPECBfield.poincare_plot_type'],['../classpyoculus_1_1problems_1_1spec__pjh_1_1_s_p_e_c_p_j_h.html#a5e74948fd86adcb44a4fa53801f4ad53',1,'pyoculus.problems.spec_pjh.SPECPJH.poincare_plot_type'],['../classpyoculus_1_1problems_1_1toroidal__problem_1_1_toroidal_problem.html',1,'pyoculus.problems.toroidal_problem.ToroidalProblem.poincare_plot_type'],['../classpyoculus_1_1problems_1_1two__waves_1_1_two_waves.html',1,'pyoculus.problems.two_waves.TwoWaves.poincare_plot_type']]],
  ['poincare_5fplot_5fxlabel_5',['poincare_plot_xlabel',['../classpyoculus_1_1problems_1_1base__problem_1_1_base_problem.html#abbed494fc030e726b920e81d98133b7c',1,'pyoculus.problems.base_problem.BaseProblem.poincare_plot_xlabel'],['../classpyoculus_1_1problems_1_1cylindrical__problem_1_1_cylindrical_problem.html',1,'pyoculus.problems.cylindrical_problem.CylindricalProblem.poincare_plot_xlabel'],['../classpyoculus_1_1problems_1_1qfm__bfield_1_1_q_f_m_bfield.html',1,'pyoculus.problems.qfm_bfield.QFMBfield.poincare_plot_xlabel'],['../classpyoculus_1_1problems_1_1spec__bfield_1_1_s_p_e_c_bfield.html',1,'pyoculus.problems.spec_bfield.SPECBfield.poincare_plot_xlabel'],['../classpyoculus_1_1problems_1_1spec__pjh_1_1_s_p_e_c_p_j_h.html#ade5d554ce3b479e3b24742f25136f1be',1,'pyoculus.problems.spec_pjh.SPECPJH.poincare_plot_xlabel'],['../classpyoculus_1_1problems_1_1toroidal__problem_1_1_toroidal_problem.html',1,'pyoculus.problems.toroidal_problem.ToroidalProblem.poincare_plot_xlabel'],['../classpyoculus_1_1problems_1_1two__waves_1_1_two_waves.html',1,'pyoculus.problems.two_waves.TwoWaves.poincare_plot_xlabel']]],
  ['poincare_5fplot_5fylabel_6',['poincare_plot_ylabel',['../classpyoculus_1_1problems_1_1base__problem_1_1_base_problem.html#a1f5df1dc731cd9638935ba322cacdbad',1,'pyoculus.problems.base_problem.BaseProblem.poincare_plot_ylabel'],['../classpyoculus_1_1problems_1_1cylindrical__problem_1_1_cylindrical_problem.html',1,'pyoculus.problems.cylindrical_problem.CylindricalProblem.poincare_plot_ylabel'],['../classpyoculus_1_1problems_1_1qfm__bfield_1_1_q_f_m_bfield.html',1,'pyoculus.problems.qfm_bfield.QFMBfield.poincare_plot_ylabel'],['../classpyoculus_1_1problems_1_1spec__bfield_1_1_s_p_e_c_bfield.html',1,'pyoculus.problems.spec_bfield.SPECBfield.poincare_plot_ylabel'],['../classpyoculus_1_1problems_1_1spec__pjh_1_1_s_p_e_c_p_j_h.html#ac5a857c5a91e24c986814e8a88874bf7',1,'pyoculus.problems.spec_pjh.SPECPJH.poincare_plot_ylabel'],['../classpyoculus_1_1problems_1_1toroidal__problem_1_1_toroidal_problem.html',1,'pyoculus.problems.toroidal_problem.ToroidalProblem.poincare_plot_ylabel'],['../classpyoculus_1_1problems_1_1two__waves_1_1_two_waves.html',1,'pyoculus.problems.two_waves.TwoWaves.poincare_plot_ylabel']]],
  ['pp_7',['pp',['../classpyoculus_1_1solvers_1_1fixed__point_1_1_fixed_point.html#a1fb676f26a1314a37285f83898f0114c',1,'pyoculus::solvers::fixed_point::FixedPoint']]],
  ['problem_5fsize_8',['problem_size',['../classpyoculus_1_1problems_1_1base__problem_1_1_base_problem.html#a6028474530347791fdef7d8c1c31844a',1,'pyoculus.problems.base_problem.BaseProblem.problem_size'],['../classpyoculus_1_1problems_1_1cylindrical__problem_1_1_cylindrical_problem.html',1,'pyoculus.problems.cylindrical_problem.CylindricalProblem.problem_size'],['../classpyoculus_1_1problems_1_1spec__bfield_1_1_s_p_e_c_bfield.html',1,'pyoculus.problems.spec_bfield.SPECBfield.problem_size'],['../classpyoculus_1_1problems_1_1spec__pjh_1_1_s_p_e_c_p_j_h.html#a4e6ebd4d4bc64f03aa24f520dd33b339',1,'pyoculus.problems.spec_pjh.SPECPJH.problem_size'],['../classpyoculus_1_1problems_1_1toroidal__problem_1_1_toroidal_problem.html',1,'pyoculus.problems.toroidal_problem.ToroidalProblem.problem_size'],['../classpyoculus_1_1problems_1_1two__waves_1_1_two_waves.html',1,'pyoculus.problems.two_waves.TwoWaves.problem_size']]]
];
